### ISSUE TITLE
ic-705 wird nicht erkannt

### ISSUE THREAD

**Issue by octavia75** [pe-jot/QtCIV#1]
Hallo, leider wird der icom nicht erkannt unter Windows 10 .

schön wäre wenn z.b. auch virtuelle com port und oder z.b. omni-rig , hamlib verwendet werden könnte

**Comment by pe-jot** [comment]
As there might be other viewers as well, I prefer to respond in English...

Detecting an Icom transceiver happens in IC705Serial::FindIcomPortName() where it gets all available COM ports from the system. Which means, as long as the transceiver device shows up in the Windows Device Manager ("Geräte-Manager") as COM port, it should find it.
In the next step, it tries to establish a CI-V communication to the device which needs to have the default CI-V address A4h. Maybe your transceiver is not set up properly for CI-V communication?

I have developed and tested this software with a Windows 10 environment, so generally the OS shouldn't be an issue.

Generally spoken, this project was done for a ham radio project and as a learning project. Due to various reasons it is not planned to do any further development at the moment, but please feel free to fork the code and adapt / extend it to your needs.

73
